valor = float(input('\n Digite o valor da prestação:'))
taxa  = float(input('\n Digite a taxa: '))
tempo = int(input('\n Digite o tempo (Número de Meses):'))
prest = valor + ( valor * (taxa / 100 )* tempo )
print(f'\n O Valor da Ptrestação em atraso é {prest}')
print('\n')